const requests = [
    {
      id: 1,
      bloodType: "A+",
      name: "Gufi",
      age: 42,
      gender: "Male",
      city: 'Karachi',
      time: 23,
      priority: "Donor",
    },
    {
      id: 2,
      bloodType: "AB-",
      name: "Fabiha",
      age: 49,
      gender: "Female",
      city: 'Gujrat',
      time: 24,
      priority: "Donor",
    },
    {
      id: 3,
      bloodType: "B+",
      name: "Bilal Sahb",
      age: 36,
      gender: "Male",
      city: 'Islamabad',
      time: 34,
      priority: "Donor",
    }, {
      id: 4,
      bloodType: "O-",
      name: "Sikander",
      age: 36,
      gender: "Male",
      city: 'Hyderabad',
      time: 24,
      priority: "Donor",
    },
    , {
      id: 5,
      bloodType: "A-",
      name: "Akhtar",
      age: 52,
      gender: "Male",
      city: 'Kashmir',
      time:35,
      priority: "Donor",
    },
    , {
      id: 6,
      bloodType: "AB-",
      name: "Ilyas khan",
      age: 43,
      gender: "Male",
      city: 'FATA',
      time: 44,
      priority: "Donor",
    },{
      id: 5,
      bloodType: "A-",
      name: "Akhtar",
      age: 52,
      gender: "Male",
      city: 'Kashmir',
      time:35,
      priority: "Donor",
    },
    , {
      id: 6,
      bloodType: "AB-",
      name: "Ilyas khan",
      age: 43,
      gender: "Male",
      city: 'FATA',
      time: 44,
      priority: "Donor",
    },{
      id: 5,
      bloodType: "A-",
      name: "Akhtar",
      age: 52,
      gender: "Male",
      city: 'Kashmir',
      time:35,
      priority: "Donor",
    },
    , {
      id: 6,
      bloodType: "AB-",
      name: "Ilyas khan",
      age: 43,
      gender: "Male",
      city: 'FATA',
      time: 44,
      priority: "Donor",
    },
  
  ];
  
  const chart = [
    1.1,
    3,
    1.5,
    2.3,
    3.2,
    7,
    8.2,
    1.2,
    2,
    1.2,
    8,
    3.8,
    5.8,
    3.9,
    5.1,
    0.1,
    6
  ];
  
 
  export { requests, chart }